//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Inspection = new HashSet<Inspection>();
            this.RentAndRefund = new HashSet<RentAndRefund>();
        }
    
        public int VehicleId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string ChasisNo { get; set; }
        public string MotorNo { get; set; }
        public string PlateNo { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual FuelType FuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentAndRefund> RentAndRefund { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
